# Association Rules

In [1]:
import pandas as pd
import warnings

### Data Preprocessing:

In [2]:
# Load and read the given dataset
warnings.simplefilter('ignore')
data=pd.read_excel('Online retail.xlsx')

In [3]:
data.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [4]:
data

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [5]:
# Handling Missing Values.
data.dropna(inplace=True)

In [6]:
data.head(10)

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt
5                     whole wheat pasta,french fries
6                           soup,light cream,shallot
7              frozen vegetables,spaghetti,green tea
8                                       french fries
9                                      eggs,pet food

In [7]:
# Removing Duplicate Rows
data.drop_duplicates(inplace=True)

In [8]:
data.head(20)

   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                              burgers,meatballs,eggs
1                                             chutney
2                                      turkey,avocado
3   mineral water,milk,energy bar,whole wheat rice...
4                                      low fat yogurt
5                      whole wheat pasta,french fries
6                            soup,light cream,shallot
7               frozen vegetables,spaghetti,green tea
8                                        french fries
9                                       eggs,pet food
10                                            cookies
11      turkey,burgers,mineral water,eggs,cooking oil
12                        spaghetti,champagne,cookies
13                               mineral water,salmon
14                                      mineral water
15  shrimp,chocolate,chicken,honey,oil,cooking oil...
16                                        turkey,eggs
17  turkey,fresh tuna,tomatoes,spaghetti,mineral w...
18      meatballs,milk,honey,french fries,protein bar
19  red wine,shrimp,pasta,pepper,eggs,chocolate,sh...

In [9]:
data.columns=['Items']

In [10]:
# Splitting the Items into Lists.
trans=data['Items'].str.split(',').apply(lambda x:[item.strip() for item in x if item])

In [11]:
# Converting to One-Hot Encoding format.
from mlxtend.preprocessing import TransactionEncoder
Te=TransactionEncoder()
data_Te=Te.fit(trans).transform(trans)
df=pd.DataFrame(data_Te,columns=Te.columns_)

In [12]:
data.head(20)

                                                Items
0                              burgers,meatballs,eggs
1                                             chutney
2                                      turkey,avocado
3   mineral water,milk,energy bar,whole wheat rice...
4                                      low fat yogurt
5                      whole wheat pasta,french fries
6                            soup,light cream,shallot
7               frozen vegetables,spaghetti,green tea
8                                        french fries
9                                       eggs,pet food
10                                            cookies
11      turkey,burgers,mineral water,eggs,cooking oil
12                        spaghetti,champagne,cookies
13                               mineral water,salmon
14                                      mineral water
15  shrimp,chocolate,chicken,honey,oil,cooking oil...
16                                        turkey,eggs
17  turkey,fresh tuna,tomatoes,spaghetti,mineral w...
18      meatballs,milk,honey,french fries,protein bar
19  red wine,shrimp,pasta,pepper,eggs,chocolate,sh...

In [13]:
df.head(10)

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### Association Rule Mining :

In [14]:
# Import required libraries
from mlxtend.frequent_patterns import apriori,association_rules

In [15]:
# Applying Apriori algorith to find frequent itemsets.
freq_itemsets=apriori(df,min_support=0.01,use_colnames=True)

In [16]:
freq_itemsets.head(10)

    support             itemsets
0  0.029179            (almonds)
1  0.011014  (antioxydant juice)
2  0.045797            (avocado)
3  0.012560              (bacon)
4  0.015459     (barbecue sauce)
5  0.020483          (black tea)
6  0.013140        (blueberries)
7  0.016232         (body spray)
8  0.045024           (brownies)
9  0.012367          (bug spray)

In [17]:
# Generation of Association Rules.
rules=association_rules(freq_itemsets,metric="confidence",min_threshold=0.2)

In [18]:
# Filtering rules Based on Metrics.
rules=rules[rules['lift']>1.0]

In [19]:
rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,(almonds),(mineral water),0.010821,0.370861,1.237399
1,(avocado),(chocolate),0.010242,0.223629,1.089716
2,(avocado),(french fries),0.011594,0.253165,1.314069
3,(avocado),(milk),0.010821,0.236287,1.389528
4,(avocado),(mineral water),0.015845,0.345992,1.154421
...,...,...,...,...,...
350,"(shrimp, spaghetti)",(mineral water),0.012367,0.407643,1.360125
351,"(soup, mineral water)",(spaghetti),0.010821,0.323699,1.410054
352,"(soup, spaghetti)",(mineral water),0.010821,0.523364,1.746235
353,"(tomatoes, mineral water)",(spaghetti),0.013527,0.391061,1.703487
354,"(tomatoes, spaghetti)",(mineral water),0.013527,0.451613,1.506832

In [20]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(mineral water),0.029179,0.299710,0.010821,0.370861,1.237399,1.0,0.002076,1.113092,0.197619,0.034022,0.101602,0.203483
1,(avocado),(chocolate),0.045797,0.205217,0.010242,0.223629,1.089716,1.0,0.000843,1.023715,0.086281,0.042536,0.023165,0.136767
2,(avocado),(french fries),0.045797,0.192657,0.011594,0.253165,1.314069,1.0,0.002771,1.081019,0.250476,0.051107,0.074947,0.156673
3,(avocado),(milk),0.045797,0.170048,0.010821,0.236287,1.389528,1.0,0.003034,1.086732,0.293786,0.052780,0.079810,0.149962
4,(avocado),(mineral water),0.045797,0.299710,0.015845,0.345992,1.154421,1.0,0.002120,1.070766,0.140185,0.048066,0.066089,0.199430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"(shrimp, spaghetti)",(mineral water),0.030338,0.299710,0.012367,0.407643,1.360125,1.0,0.003274,1.182210,0.273058,0.038929,0.154126,0.224454
351,"(soup, mineral water)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,1.0,0.003147,1.139190,0.300865,0.042912,0.122183,0.185419
352,"(soup, spaghetti)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,1.0,0.004624,1.469236,0.436362,0.034956,0.319374,0.279735
353,"(tomatoes, mineral water)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,1.0,0.005586,1.265209,0.427765,0.053971,0.209617,0.224992
354,"(tomatoes, spaghetti)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,1.0,0.004550,1.276999,0.346742,0.042787,0.216914,0.248373

In [21]:
rules_sort=rules.sort_values(by='lift',ascending=False)

In [22]:
rules_sort[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head()

,antecedents,consequents,support,confidence,lift
176,(whole wheat pasta),(olive oil),0.011014,0.271429,3.100757
126,(herb & pepper),(ground beef),0.022802,0.343023,2.525100
312,"(shrimp, mineral water)",(frozen vegetables),0.010435,0.312139,2.403747
305,"(spaghetti, frozen vegetables)",(ground beef),0.012560,0.321782,2.368738
343,"(milk, spaghetti)",(olive oil),0.010242,0.204633,2.337697

In [23]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(mineral water),0.029179,0.299710,0.010821,0.370861,1.237399,1.0,0.002076,1.113092,0.197619,0.034022,0.101602,0.203483
1,(avocado),(chocolate),0.045797,0.205217,0.010242,0.223629,1.089716,1.0,0.000843,1.023715,0.086281,0.042536,0.023165,0.136767
2,(avocado),(french fries),0.045797,0.192657,0.011594,0.253165,1.314069,1.0,0.002771,1.081019,0.250476,0.051107,0.074947,0.156673
3,(avocado),(milk),0.045797,0.170048,0.010821,0.236287,1.389528,1.0,0.003034,1.086732,0.293786,0.052780,0.079810,0.149962
4,(avocado),(mineral water),0.045797,0.299710,0.015845,0.345992,1.154421,1.0,0.002120,1.070766,0.140185,0.048066,0.066089,0.199430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"(shrimp, spaghetti)",(mineral water),0.030338,0.299710,0.012367,0.407643,1.360125,1.0,0.003274,1.182210,0.273058,0.038929,0.154126,0.224454
351,"(soup, mineral water)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,1.0,0.003147,1.139190,0.300865,0.042912,0.122183,0.185419
352,"(soup, spaghetti)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,1.0,0.004624,1.469236,0.436362,0.034956,0.319374,0.279735
353,"(tomatoes, mineral water)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,1.0,0.005586,1.265209,0.427765,0.053971,0.209617,0.224992
354,"(tomatoes, spaghetti)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,1.0,0.004550,1.276999,0.346742,0.042787,0.216914,0.248373

### Analysis and Interpretation :

In [24]:
print(rules_sort.head(10))

                            antecedents          consequents  \
176                 (whole wheat pasta)          (olive oil)
126                     (herb & pepper)        (ground beef)
312             (shrimp, mineral water)  (frozen vegetables)
305      (spaghetti, frozen vegetables)        (ground beef)
343                   (milk, spaghetti)          (olive oil)
304    (ground beef, frozen vegetables)          (spaghetti)
338               (soup, mineral water)               (milk)
188                (eggs, french fries)            (burgers)
330          (spaghetti, mineral water)        (ground beef)
313  (mineral water, frozen vegetables)             (shrimp)

     antecedent support  consequent support   support  confidence      lift  \
176            0.040580            0.087536  0.011014    0.271429  3.100757
126            0.066473            0.135845  0.022802    0.343023  2.525100
312            0.033430            0.129855  0.010435    0.312139  2.403747
305            0.039034            0.135845  0.012560    0.321782  2.368738
343            0.050048            0.087536  0.010242    0.204633  2.337697
304            0.024541            0.229565  0.012560    0.511811  2.229480
338            0.033430            0.170048  0.012367    0.369942  2.175512
188            0.046377            0.113816  0.011401    0.245833  2.159911
330            0.085024            0.135845  0.024734    0.290909  2.141472
313            0.050435            0.098744  0.010435    0.206897  2.095283

     representativity  leverage  conviction  zhangs_metric   jaccard  \
176               1.0  0.007462    1.252401       0.706154  0.094059
126               1.0  0.013772    1.315350       0.646983  0.127018
312               1.0  0.006094    1.265001       0.604181  0.068268
305               1.0  0.007258    1.274155       0.601306  0.077381
343               1.0  0.005861    1.147224       0.602377  0.080425
304               1.0  0.006927    1.578149       0.565339  0.052000
338               1.0  0.006682    1.317263       0.559026  0.064712
188               1.0  0.006123    1.175050       0.563134  0.076623
330               1.0  0.013184    1.218680       0.582563  0.126108
313               1.0  0.005455    1.136366       0.550502  0.075209

     certainty  kulczynski
176   0.201534    0.198628
126   0.239746    0.255438
312   0.209487    0.196248
305   0.215166    0.207122
343   0.128331    0.160815
304   0.366346    0.283262
338   0.240850    0.221335
188   0.148972    0.173002
330   0.179440    0.236493
313   0.120002    0.156286

### Interview Questions:

#### 1.What is lift and why is it important in Association rules?
Lift is a measure that helps you understand how much more likely two items are to appear together compared to if they were independent. It tells you if there's a meaningful relationship between two items or events beyond random chance.

Lift indicates how much more likely one item is found with another than by pure chance. A lift greater than 1 shows a positive association (the items often appear together), while a lift less than 1 suggests a negative association (they rarely appear together). A lift of exactly 1 implies no relationship.

#### 2.What is support and Confidence. How do you calculate them?
Support measures how frequently an item or a combination of items appears in the dataset. It’s a measure of the general frequency of occurrence, which helps in identifying common itemsets.

Formula: Support(𝐴→𝐵)=Transactions containing 𝐴 and 𝐵/Total transactions​

Confidence is a measure of how often items in an association rule are found together. Specifically, it measures the likelihood of finding item B in a transaction if item A is already present.

Formula: Confidence(𝐴→𝐵)=Transactions containing 𝐴 and 𝐵/Transactions containing 𝐴

#### 3.What are some limitations or challenges of Association rules mining?
Scalability: With large datasets, the number of possible item combinations can be enormous, leading to high computational costs.

Threshold Selection: Setting support and confidence thresholds is tricky. Too low, and you get an overwhelming number of rules; too high, and you might miss potentially useful associations.

Relevancy: Not all discovered rules are useful or interesting; filtering out trivial or irrelevant rules can be challenging.